### ISSUE TITLE
Updates for a few entries

### ISSUE THREAD

**Issue by radtkea** [IBEXImagingCommunity/ibex_imaging_knowledge_base#81]
Change tissue state from "Metastatic ovarian cancer" to "NA" for tonsil entries found below (2 separate instances): 
https://ibeximagingcommunity.github.io/ibex_imaging_knowledge_base/supporting_material/Alpha_smooth_muscle_actin_AF488/0000-0001-9561-4256.html

https://ibeximagingcommunity.github.io/ibex_imaging_knowledge_base/supporting_material/Alpha_smooth_muscle_actin_AF488/0000-0001-9561-4256.html

Thanks!

**Comment by zivy** [comment]
Hello @radtkea,

These are the same instance. Please provide the link to the second instance.

**Comment by radtkea** [comment]
@zivy 

Sorry about that. Try this link: https://ibeximagingcommunity.github.io/ibex_imaging_knowledge_base/supporting_material/CD11b_AF647/0000-0001-9561-4256.html

Thanks!
A
